name: instagram
description: instagram app.

publish_to: 'none'

version: 3.4.4

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  cloud_firestore: ^6.0.0
  firebase_auth: ^6.0.1
  firebase_core: ^4.0.0
  firebase_storage: ^13.0.0
  firebase_crashlytics: ^5.0.0
  flutter_svg: ^2.2.0
  readmore: ^3.0.0
  equatable: ^2.0.5
  fluttertoast: ^8.2.1
  get_it: ^7.3.0
  shared_preferences: ^2.1.0
  pull_to_refresh:
    git:
      url: https://github.com/peng8350/flutter_pulltorefresh
  carousel_slider: ^4.2.1
  inview_notifier_list: ^3.0.0
  audioplayers: ^5.1.0
  audio_video_progress_bar: ^2.0.0
  flutter_phoenix: ^1.1.1
  easy_localization: ^3.0.2
  animated_text_kit: ^4.2.2
  record: ^6.1.1
  flutter_image_compress: ^1.1.3
  image_picker: ^1.0.4
  flutter_staggered_grid_view: ^0.4.1
  cached_network_image: ^3.2.3
  video_player: ^2.7.0
  shimmer: ^3.0.0
  get_storage: ^2.1.1
  blurhash: ^1.1.1
  get: ^4.6.5
  video_thumbnail: ^0.5.3
  permission_handler: ^10.4.3
  overlay_support: ^2.1.0
  flutter_blurhash: ^0.7.0
  path_provider: ^2.1.1
  animated_splash_screen: ^1.3.0
  firebase_messaging: ^16.0.0
  agora_rtc_engine: ^5.3.0
  flutter_local_notifications: ^9.7.0
  scrollable_positioned_list: ^0.3.8
  flutter_launcher_icons: ^0.13.1

  # My package
  image_picker_plus: ^0.5.9

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/instagram.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/play_store_512.png"

flutter:

  uses-material-design: true
  assets:
    - assets/icons/
    - assets/splash/